# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/s3ve3g-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter afyonltecan afyonltetmo afyonlteMetroPCS,$(TARGET_DEVICE)),)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libtime_genoff
#LOCAL_MODULE_OWNER := samsung
#LOCAL_SRC_FILES := proprietary/vendor/lib/libtime_genoff.so
#LOCAL_MULTILIB := 32
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_VENDOR_MODULE := true
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TimeService
LOCAL_MODULE_OWNER := samsung
LOCAL_SRC_FILES := proprietary/app/TimeService/TimeService.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

endif
